apiVersion: v1
kind: ReplicationController
metadata:
  name: cas-dto-web-rc
  labels:
    name: cas-dto-web
    context: cas-dto-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cas-dto-web
        context: cas-dto-web
    spec:
      containers:
      - name: cas-dto-web-rc-pod
        image: gustvegas/cas-dto-web:0.4
        ports:
        - containerPort: 3000
