apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pssim-api-1
  labels:
    app: pssim-api-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pssim-api-1
  template:
    metadata:
      labels:
        app: pssim-api-1
    spec:
      hostAliases:
      - ip: "172.16.50.58"
        hostnames:
        - "minvu.ldap"
      - ip: "10.40.5.44"
        hostnames:
        - "minvu.db"
      containers:
      - name: pssim-api-1
        image: minvu.azurecr.io/pssim-api:funciona
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
