apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  labels:
    app: nginx-1
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx-1
        image: gcr.io/google_containers/nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-svc-1
  labels:
    app: http-svc-1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-svc-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: http-svc-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-svc-1
    spec:
      containers:
      - name: http-svc-1
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-tls-1
  namespace: default
spec:
  rules:
  - host: foo.bar1.com
    http:
      paths:
      - backend:
          serviceName: http-svc-1
          servicePort: 80
        path: /
  - host: bar.baz.com
    http:
      paths:
      - backend:
          serviceName: nginx-1
          servicePort: 80
        path: /
