apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  name: rewrite
  namespace: default
spec:
  rules:
  - host: catastro.minvu2.cl
    http:
      paths:
      - backend:
          serviceName: pssim-api-10-service
          servicePort: 80
        path: /something
        
