apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pssim-api-3-pod
  labels:
    app: pssim-api-3
spec:
  containers:
  - name: pssim-api-3-container
    image: ivancaro/test:latest
    ports:
    - containerPort: 80
      protocol: TCP
